services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_DEBUG=false
      - BCRYPT_ROUNDS=12
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/pwdncrypt"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Development service with hot reload
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app/app:ro
      - ./tests:/app/tests:ro
    environment:
      - PORT=5000
      - FLASK_DEBUG=true
      - BCRYPT_ROUNDS=4
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/pwdncrypt"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s 