name: App Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test production image
      run: |
        docker compose build api
        docker compose up -d api
        # Wait for container to be ready and healthy
        echo "Waiting for production container to be ready..."
        timeout 30s bash -c 'while ! curl -s http://localhost:5000/pwdncrypt > /dev/null; do sleep 1; done'
        # Test the API endpoints
        curl -v http://localhost:5000/pwdncrypt
        docker compose logs api
        docker compose down

    - name: Build and test development image
      run: |
        docker compose build api-dev
        docker compose up -d api-dev
        # Wait for container to be ready and healthy
        echo "Waiting for development container to be ready..."
        timeout 30s bash -c 'while ! curl -s http://localhost:5001/pwdncrypt > /dev/null; do sleep 1; done'
        # Test the API endpoints
        curl -v http://localhost:5001/pwdncrypt
        docker compose logs api-dev
        docker compose down

    - name: Run tests in container
      run: |
        # Run tests with proper network setup
        docker compose run --rm \
          --network host \
          api-dev pytest 