name: App Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test production image
      run: |
        docker compose build api
        docker compose up -d api
        # Wait for container to be ready
        sleep 10
        # Test the API endpoints
        curl -f http://localhost:5000/pwdncrypt || exit 1
        docker compose down

    - name: Build and test development image
      run: |
        docker compose build api-dev
        docker compose up -d api-dev
        # Wait for container to be ready
        sleep 10
        # Test the API endpoints
        curl -f http://localhost:5001/pwdncrypt || exit 1
        docker compose down

    - name: Run tests in container
      run: |
        docker compose run --rm api-dev pytest 