name: Create Release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build check
      run: docker compose build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

    - name: Create tag
      run: |
        git tag v${{ steps.timestamp.outputs.timestamp }}
        git push origin v${{ steps.timestamp.outputs.timestamp }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.timestamp.outputs.timestamp }}
        name: Release v${{ steps.timestamp.outputs.timestamp }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 